bua/views_and_forms/main/routes.py
from flask_login import current_user
from sqlalchemy import func

from bua import db
from bua.models import Task, Squad, Todo
from flask import Flask, render_template, request, redirect, url_for, Blueprint, abort, flash

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    squads = Squad.query.order_by(Squad.id.desc())
    return render_template('main/home.html', squads=squads)


@main.route("/about")
def about():
    return render_template('main/about.html', title='About')



@main.route("/")
@main.route("/your_squad")
def all_squad():


    activity_count = db.session.query(Task.activity).count()

    members = (db.session.query(Squad).filter(Squad.id).first())

    vol_sum = db.session.query(func.sum(Task.volume)).scalar()/activity_count
    time_sum = db.session.query(func.sum(Task.avg_time)).scalar()
    ftes = (((((vol_sum) * (time_sum))*12)/60)/1975)

    waste_time = db.session.query(func.sum(Task.pain_point_time)).scalar()
    w_t_hrs_per_Month = (((waste_time)*(vol_sum))/60)

    tasks = Task.query.order_by(Task.date_posted.desc())

    affected_volume = db.session.query(func.sum(Todo.affected_volume)).scalar()
    saving_sum = db.session.query(func.sum(Todo.saving)).scalar()
    saving_ftes = (((((saving_sum) * (affected_volume)) * 12) / 60) / 1975)

    squad_members = db.session.query(func.sum(Squad.squad_members)).scalar()
    capacity_open = (squad_members-ftes)


    return render_template('main/all_squad.html',
                           tasks=tasks,
                           squad_members=squad_members,


                           activity_count=activity_count,
                           time_sum=time_sum, vol_sum=vol_sum,
                           ftes=ftes, waste_time=waste_time,
                           w_t_hrs_per_Month=w_t_hrs_per_Month,
                           saving_ftes=saving_ftes,
                           capacity_open=capacity_open
                           )

@main.route("/task/<int:task_id>")
def task(task_id):
        task = Task.query.get_or_404(task_id)

        tftes = (((int(task.volume) * int(task.avg_time)*12)/60)/1975)


        return render_template('main/all_squad.html', task=task, tftes=tftes)

bua/views_and_forms/squads/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from sqlalchemy import func

from bua import db, bcrypt
from bua.models import Squad, Task, Todo
from bua.views_and_forms.squads.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from bua.views_and_forms.squads.utils import save_picture, send_reset_email


squads = Blueprint('squads', __name__)



@squads.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        squad = Squad(squadname=form.squadname.data, email=form.email.data, squad_members=form.squad_members.data, password=hashed_password)

        db.session.add(squad)
        db.session.commit()

        return redirect(url_for('squads.login'))
    return render_template('squad/register.html', title='Register', form=form)


@squads.route("/log", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        squad = Squad.query.filter_by(email=form.email.data).first()
        if squad and bcrypt.check_password_hash(squad.password, form.password.data):
            login_user(squad, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('squad/login.html', title='Login', form=form)


@squads.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@squads.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.squadname = form.squadname.data
        current_user.squad_members = form.squad_members.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('squads.account'))
    elif request.method == 'GET':
        form.squadname.data = current_user.squadname
        form.squad_members.data = current_user.squad_members
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('main/account.html', title='Account',
                           image_file=image_file, form=form)


def sum_fte(task_id):
    taskid = Task.query.get_or_404(task_id).escalar()
    task_ftes = (((int(taskid.volume) * int(taskid.avg_time) * 12) / 60) / 1975)
    #def my_filter(query):
     #   return query.filter_by(name='wendy')
    #wendy = my_filter(session.query(User)).one()


@squads.route("/squad/<squadname>")



def squad_detail(squadname):

    squad = Squad.query.filter_by(squadname=squadname).first_or_404()
    tasks = Task.query.filter_by(author=squad)\
        .order_by(Task.date_posted.desc())

    activity_count = Task.query.filter_by(author=squad).count()

    vol_sum = db.session.query(func.sum(Task.volume)).filter_by(author=squad).scalar()/activity_count
    time_sum = db.session.query(func.sum(Task.avg_time)).filter_by(author=squad).scalar()
    squad_ftes = (((((vol_sum) * (time_sum)) * 12) / 60) / 1975)

    standard_activity_count = Task.query.filter_by(author=squad).filter(Task.pain_point=="Standard").count()

    standard_vol = db.session.query(func.sum(Task.volume)).filter_by(author=squad).filter(Task.pain_point=="Standard").scalar()/standard_activity_count
    standard_time_sum = db.session.query(func.sum(Task.avg_time)).filter_by(author=squad).filter(Task.pain_point=="Standard").scalar()
    standard_ftes = (((((standard_vol) * (standard_time_sum)) * 12) / 60) / 1975)


    return render_template('tasks/squad_details.html',
                           tasks=tasks, squad=squad,
                           activity_count=activity_count,
                           squad_ftes=squad_ftes,
                           standard_ftes=standard_ftes,
                           )


@squads.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        squad = Squad.query.filter_by(email=form.email.data).first()
        send_reset_email(squad)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('squads.login'))
    return render_template('squad/reset_request.html', title='Reset Password', form=form)


@squads.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    squad = Squad.verify_reset_token(token)
    if squad is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('squads.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        squad.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('squads.login'))
        return render_template('squad/reset_token.html', title='Reset Password', form=form)

bua/views_and_forms/tasks/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from sqlalchemy import func

from bua import db
from bua.models import Task
from bua.views_and_forms.tasks.forms import TaskForm

tasks = Blueprint('tasks', __name__)


@tasks.route("/task/new", methods=['GET', 'POST'])
@login_required
def new_task():
    form = TaskForm()
    if form.validate_on_submit():
        activity = Task(
                        activity=form.activity.data,
                        tool=form.tool.data,
                        product=form.product.data,
                        summary=form.summary.data,

                        avg_time=form.avg_time.data,
                        volume=form.volume.data,

                        pain_point=form.pain_point.data,
                        pain_point_time=form.pain_point_time.data,

                        author=current_user)
        db.session.add(activity)
        db.session.commit()
        flash('Your activity has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('tasks/create_task.html', title='New Task',
                           form=form, legend='New Task')


@tasks.route("/task/<int:task_id>")
def task(task_id):
        task = Task.query.get_or_404(task_id)


        ftes = (((int(task.volume) * int(task.avg_time)*12)/60)/1975)


        waste_time = (task.pain_point_time)
        return render_template('tasks/task.html', task=task, ftes=ftes, waste_time=waste_time)


#movies[(movies.duration=>200) & (movies.genre == 'Drama')]
#movies[(movies.duration=>200) | (movies.genre == 'Drama')]
#movies[movies.genre.isin(["crime", 'drama', 'action'])]
#

@tasks.route("/task/<int:task_id>/update", methods=['GET', 'POST'])
@login_required
def update_task(task_id):
    task = Task.query.get_or_404(task_id)
    if task.author != current_user:
        abort(403)
    form = TaskForm()
    if form.validate_on_submit():

        task.activity = form.activity.data
        task.tool = form.tool.data
        task.product = form.product.data
        task.summary = form.summary.data

        task.avg_time = form.avg_time.data
        task.volume = form.volume.data

        task.pain_point = form.pain_point.data
        task.pain_point_time = form.pain_point_time.data

        author = current_user
        db.session.commit()
        flash('Your task has been updated!', 'success')
        return redirect(url_for('main.home', task_id=task.id))
    elif request.method == 'GET':

        form.activity.data = task.activity
        form.tool.data = task.tool
        form.product.data = task.product
        form.summary.data = task.summary

        form.avg_time.data = task.avg_time
        form.volume.data = task.volume

        form.pain_point.data = task.pain_point
        form.pain_point_time.data = task.pain_point_time

        author = current_user
    return render_template('tasks/create_task.html', title='Update Post',
                           form=form, legend='Update Post')


@tasks.route("/task/<int:task_id>/delete", methods=['POST'])
@login_required
def delete_task(task_id):
    task = Task.query.get_or_404(task_id)

    db.session.delete(task)
    db.session.commit()
    flash('Your task has been deleted!', 'danger')
    return redirect(url_for('main.home'))

bua/templates/main/_layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% if title %}
      <title>Bottoms Up Analysis - {{ title }}</title>
    {% else %}
      <title>Bottoms Up Analysis</title>
    {% endif %}

    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,600,600italic,700,700italic|Source+Code+Pro:500">
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" href="/static/css/nav.css"/>
    {% block additional_css %}{% endblock %}
</head>

<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container home-main">
        <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">Bottoms Up Analysis</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-titles">
              {% if current_user.is_authenticated %}
                  {% if current_user.role == "user" %}
                      <a class="nav-item nav-link" href="{{ url_for('tasks.new_task') }}">New</a>
                      <a class="nav-item nav-link" href="{{ url_for('main.all_squad') }}">All Squads</a>

                      <a class="nav-item nav-link" href="{{ url_for('squads.account') }}">Squad Info</a>
                      <a class="nav-item nav-link" href="{{ url_for('squads.logout') }}">Logout</a>
                     {% endif %}

                  {% if current_user.role == "admin" %}
                      <a class="nav-item nav-link" href="{{ url_for('admin.index') }}">Admin</a>
                      <a class="nav-item nav-link" href="{{ url_for('squads.account') }}">Info</a>
                      <a class="nav-item nav-link" href="{{ url_for('squads.logout') }}">Logout</a>
                  {% endif %}

              {% else %}
                  <a class="nav-item nav-link" href="{{ url_for('squads.login') }}">Login</a>
                  <a class="nav-item nav-link" href="{{ url_for('squads.register') }}">Register</a>
              {% endif %}
          </div>
      </div>
</nav>

<div class="message">
<div class="col-md-12">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
</div>
 </div>

{% block content %}{% endblock %}

 <footer>
        This is a site built for Services Analysis.
        <br>It's meant to model and understand task and activities for our teams and squads
        <br> To understand more about workforce management
        <br>please review our
        <a href="{{ url_for('main.about') }}">About Page</a>.
 </footer>



<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>

{% block additional_js %}{% endblock %}

</body>
</html>

bua/templates/main/about.html
{% extends "main/_layout.html" %}
{% block additional_css %}
<link rel="stylesheet" href="/static/css/about.css"/>
{% endblock %}
{% block title %} About {% endblock %}

{% block content %}

     <div class="purpose">
        <h1>  1. Purpose </h1>
        <p>
            This Section of the application is intended to provided an overview for a Bottoms Up Web app on the concept
            of Workforce management framework focus in a functional model, operational and culture based. From a Discovery phase
            to a mature management system state, touching components for leading and collaborating with different
            part and business units of share services in an enterprise environment. The section provides an understanding
            of workforce management and the pre work, culture
        </p>
    </div>

    <div>
        <div class="form-container">


        <form action="" method="POST" class="account-form">
            <h1>1.1 Description</h1>

            <small>Enterprise performances and services among business units depend not only
                in process and tools but on our workforce who leverage our knowledge capital, having a
                visibility support and proper management in our enterprise services creates a competitive advantage for
                our services to balance, forecast and harmonized staffing levels improving our services for customer and
                employee experiences. Workforce management includes more than a simple understanding of up coming workloads
                the web app offers a platform to deeply understand tasks, knowledge, process understanding, efforts,
                communications and more importantly people. We also consider that each business unit/services/squad has
                a different level of maturity level on business intelligent and workforces analytics as the enterprise evolves
                workforce management hopes to provide a framework and approach to
                focus workforce management at any business unit maturity stage.</small>

        </form>
      </div>

        <div class="form-container">


        <form action="" method="POST" class="account-form">
            <h1>1.2 Goal</h1>

            <small>  The goal for workforce management is to establish a common culture, a management system
                set by key performance indicators harmonizing to the business day to day goals and
                objectives using best practices from Agile, Scrum, Project Management and continual improvement.
                The multiprogram should elaborate on Discovery Phase to vision the scope for any given
                business unit project. And followed by an iteration cero to initiate formalized and set
                up a diverse multifunctional team that will iterate in order to create a logic minimal
                viable product and elaborate to business goal for the business unit workforce management
                formal project The enterprise will be split in each business unit and among services creating a
                dashboard and support From a peer to peer bases generating synergy, bench marking and
                collaboration among areas and business units, creating a community and culture for
                workforce management among the business areas </small>

        </form>
      </div>









    <div class="purpose">
        <div class="hero-inner">
           <h1>  2. Program </h1>
            <p>
                The value of the program rest in the services, mentorship, networking and recognition the business areas
                can gain by enrolling into workforce management. The focus is based into the capacity open and the value
                the business unit can generate as return for the investment. Aside of looking for logical space for a
                cross functional to elaborate on a program deliverable we will focus our efforts to create a co working
                culture on every opportunity not only in a local business unit level but also globally using the best at
                hand methodologies and technologies. The process for which the program will be encourage will be based on
                the following phases or concepts:
            </p>
             1. Awareness
            <p></p>
             2. Engagement
            <p></p>
             3. Program Development
            <p></p>
             4. Demo Program Closure
            <p></p>
             5. Retrospective and Re Engagement


        </div>
    </div>

        <div class="activities-list">
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-11">
                    <div class="subtitle">
                        2.1 Phases and Ramifications
                        <hr>
                    </div>
                    <table class="phases">
                        <thead>
                            <th>Phase</th>
                            <th>Description & Goal</th>
                            <th>Components</th>
                        </thead>

                        <tbody class = "row1">

                            <td>1. Awareness</td>
                            <td>The Awareness stage provides a framework to communicate about the workforce management effort.
                                Creates different communication channels to identify big stakeholders, population and key
                                players</td>
                            <td><p>1. Initial Communications and communication planning</p>
                                <p>2. Empowerment</p>
                                <p>3. Acknowledgement</p>
                            </td>

                        </tbody>
                        <tbody class = "row2">
                            <td>2. Engagement</td>
                            <td>This stage provides the tools and structures for the business units to apply and enroll to
                                the program, adopt methodologies and frameworks while identifying a core multifunctional
                                team for the program success </td>
                            <td><p>4. Identification</p>
                                <p>5. Design Thinking</p>
                                <p>6. Agile and Scrum as framework</p></td>
                        </tbody>
                        <tbody class = "row3">
                            <td>3. Program Development</td>
                            <td>The Core stage for transformation this stage allows our business units to develop in
                                different phases their transformation strategy and adoption of the workforce management
                                tools, applications and management systems </td>
                            <td><p>7. Discovery</b>
                                <p>8. Iteration 0</p>
                                <p>9. MVP</p>
                                <p>10. Hills</p>
                            </td>
                        </tbody>
                        <tbody class = "row4">
                            <td>4. Demo Program Closure </td>
                            <td>The demo stage allows the business unit to set a finite goal and logical closure for the
                                program giving place for the business unit to celebrate, communicate and harmonized the
                                services and solutions to the day to day operations </td>
                            <td><p>11. Demo</p>
                                <p>12. Closure</p>
                                <p>13. Bench Marking</p>
                                <p>14. Business as Usual Transition</p>
                            </td>
                        </tbody>
                        <tbody class = "row5">
                            <td>5. Retrospective and re Engagement </td>
                            <td>The stage allows the business unit to identify key areas of accomplishments, opportunities,
                                close up questions, identify any new idea while opting of a second or third iteration of
                                the program.  </td>
                            <td><p>15. Maturity Assessment</p>
                                <p>16. Retrospective</p>
                                <p>17. Re Engagement</p>
                            </td>
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
{% endblock content %}

bua/templates/main/account.html
{% extends "main/_layout.html" %}
{% block title %} Account Update {% endblock %}
{% block additional_css %}
<link rel="stylesheet" href="/static/css/account.css"/>
{% endblock %}

{% block content %}
    <div class="content-section-account">

      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
          <div class="media-body">
              <h2>{{ current_user.squadname }}</h2>

              <p class="text-secondary">{{ current_user.email }}</p>
          </div>
      </div>



        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-2">Update your Account Info</legend>

                <div class="form-group">
                    {{ form.squadname.label(class="form-control-label") }}

                    {% if form.squadname.errors %}
                        {{ form.squadname(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.squadname.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.squadname(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.squad_members.label(class="form-control-label") }}

                    {% if form.squad_members.errors %}
                        {{ form.squad_members(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.squad_members.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.squad_members(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>

            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-primary") }}
            </div>
        </form>


    </div>

    <div>.</div>
</div>
{% endblock content %}

bua/templates/main/all_squad.html
{% extends "main/_layout.html" %}
{% block title %} Index {% endblock %}
{% block additional_css %}
<link rel="stylesheet" href="/static/css/home.css"/>
<link rel="stylesheet" href="/static/css/your_squad.css"/>
{% endblock %}

{% block content %}

    {% if current_user.is_authenticated %}

    <div class="hero">
       <div class="hero-inner">
           <h1> Review your Squad Activities and Workloads</h1>
        </div>
        or <a href="{{ url_for('main.about') }}">Find More About Bottoms Up Analysis</a>
    </div>

    <div class="bua-stats">
        <div class="stat"> Activities: {{ "{:,}".format(activity_count) }} </div>

        <div class="stat"> Current Workloads: {{ "{0:.1f}".format(ftes) }} <small>FTEs</small>  </div>

        <div class="stat"> Waste Time: {{ "{0:.1f}".format(w_t_hrs_per_Month) }} <small>|Hrs per Month|</small> </div>


        <div class="stat"> Members: {{ (squad_members) }}  </div>


    </div>

    <div class="content-section">
                 <h2> Tasks Overview</h2>


        <div class="table-responsive">
            <table class="table table-sm table-condensed table-striped" id="activities">
            <thead>
                <tr>
                    <th scope="col">Activity</th>
                    <th scope="col">Tool/s</th>
                    <th scope="col">Volume per Month</th>
                    <th scope="col">Min per Transaction</th>
                    <th scope="col">Feedback</th>


                </tr>
            </thead>
            <tbody>
            {% for t in tasks %}
                <tr id={{ t.id }}>
                    <td scope="col"> {{ t.activity }}</td>
                    <td scope="col"> {{ t.tool }} </td>
                    <td scope="col"> {{ t.volume }} </td>
                    <td scope="col"> {{ t.avg_time }} </td>
                    <td scope="col"> {{ t.pain_point }} </td>

                    <div class="buttons">
                        <td scope="col"> <a class="btn btn-secondary btn-sm m-1" href="/task/{{ t.id }}">More</a> </td>

                    </div>
                </tr>
            {% endfor %}
            <div class="todo">
            </tbody>
        </table>
                     <td scope="col"> <a class="btn btn-success btn-sm m-1" href="{{ url_for('todo.to_do') }}">Actions & Savings </a></td>

        </div>

    </div>
{% endif %}


{% endblock content %}

bua/templates/main/home.html
{% extends "main/_layout.html" %}
{% block title %} Index {% endblock %}
{% block additional_css %}
<link rel="stylesheet" href="/static/css/home.css"/>
{% endblock %}

{% block content %}
    <div class="hero">
        <div class="hero-inner">
           <h1> Retrieve any activities & workloads </h1>
        </div>
        or <a href="{{ url_for('main.about') }}">Find More About Bottoms Up Analysis</a>
    </div>

    {% if current_user.is_authenticated %}

    <div class="squads-list">
        <div class="row">
            <div class="col-md-3"></div>

            <div class="col-md-7">
                <h2> Squads List</h2>
                {% for squad in squads %}

                    <article class="media content-section">
                        <div class="media-body">
                            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + squad.image_file) }}">
                             <a class="mr-2" href="{{ url_for('squads.squad_detail', squadname=squad.squadname) }}">{{ squad.squadname }} </a>

                            <p> Members = {{ squad.squad_members }}</p>
                            <div class="article-metadata">
                        </div>
                    </article>
                {% endfor %}
            </div>

            </div>
        </div>
   </div>
    {% endif %}



{% endblock content %}