bua/views_and_forms/tasks/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length


class TaskForm(FlaskForm):

    activity = StringField('Activity', validators=[DataRequired()])
    tool = StringField('Tool', validators=[DataRequired()])
    product = TextAreaField('Product', validators=[DataRequired()])
    summary = TextAreaField('Summary', validators=[DataRequired()])

    avg_time = StringField('Min. per Transaction', validators=[DataRequired(), Length(min=1, max=5)])
    volume = StringField('Volume per Month', validators=[DataRequired(), Length(min=1, max=5)])

    pain_point = TextAreaField('Feedback', validators=[DataRequired()])
    pain_point_time = StringField('Waste Time per Transaction in Minutes', validators=[DataRequired(),Length(min=1, max=5)])

    submit = SubmitField('Submit')

bua/views_and_forms/tasks/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from sqlalchemy import func

from bua import db
from bua.models import Task
from bua.views_and_forms.tasks.forms import TaskForm

tasks = Blueprint('tasks', __name__)


@tasks.route("/task/new", methods=['GET', 'POST'])
@login_required
def new_task():
    form = TaskForm()
    if form.validate_on_submit():
        activity = Task(
                        activity=form.activity.data,
                        tool=form.tool.data,
                        product=form.product.data,
                        summary=form.summary.data,

                        avg_time=form.avg_time.data,
                        volume=form.volume.data,

                        pain_point=form.pain_point.data,
                        pain_point_time=form.pain_point_time.data,

                        author=current_user)
        db.session.add(activity)
        db.session.commit()
        flash('Your activity has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('tasks/create_task.html', title='New Task',
                           form=form, legend='New Task')


@tasks.route("/task/<int:task_id>")
def task(task_id):
        task = Task.query.get_or_404(task_id)


        ftes = (((int(task.volume) * int(task.avg_time)*12)/60)/1975)


        waste_time = (task.pain_point_time)
        return render_template('tasks/task.html', task=task, ftes=ftes, waste_time=waste_time)


#movies[(movies.duration=>200) & (movies.genre == 'Drama')]
#movies[(movies.duration=>200) | (movies.genre == 'Drama')]
#movies[movies.genre.isin(["crime", 'drama', 'action'])]
#

@tasks.route("/task/<int:task_id>/update", methods=['GET', 'POST'])
@login_required
def update_task(task_id):
    task = Task.query.get_or_404(task_id)
    if task.author != current_user:
        abort(403)
    form = TaskForm()
    if form.validate_on_submit():

        task.activity = form.activity.data
        task.tool = form.tool.data
        task.product = form.product.data
        task.summary = form.summary.data

        task.avg_time = form.avg_time.data
        task.volume = form.volume.data

        task.pain_point = form.pain_point.data
        task.pain_point_time = form.pain_point_time.data

        author = current_user
        db.session.commit()
        flash('Your task has been updated!', 'success')
        return redirect(url_for('main.home', task_id=task.id))
    elif request.method == 'GET':

        form.activity.data = task.activity
        form.tool.data = task.tool
        form.product.data = task.product
        form.summary.data = task.summary

        form.avg_time.data = task.avg_time
        form.volume.data = task.volume

        form.pain_point.data = task.pain_point
        form.pain_point_time.data = task.pain_point_time

        author = current_user
    return render_template('tasks/create_task.html', title='Update Post',
                           form=form, legend='Update Post')


@tasks.route("/task/<int:task_id>/delete", methods=['POST'])
@login_required
def delete_task(task_id):
    task = Task.query.get_or_404(task_id)

    db.session.delete(task)
    db.session.commit()
    flash('Your task has been deleted!', 'danger')
    return redirect(url_for('main.home'))

bua/templates/tasks/create_task.html
{% extends "main/_layout.html" %}
{% block additional_css %}
<link rel="stylesheet" href="/static/css/tasks.css"/>
{% endblock %}

{% block content %}

<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}

    <div class="form-group">
            <p class="title">  <h3> Task Details</h3> </p>
                 <h2> Activity Descriptions</h2>

        <div class="form-group">
            {{ form.activity.label(class="form-control-label") }}
            {% if form.activity.errors %}
                {{ form.activity(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.activity.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.activity(class="form-control form-control-lg") }}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.tool.label(class="form-control-label mb-4") }}
            {% if form.tool.errors %}
                {{ form.tool(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.tool.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.tool(class="form-control form-control-lg") }}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.product.label(class="form-control-label mb-4") }}
            {% if form.product.errors %}
                {{ form.product(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.product.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.product(class="form-control form-control-lg") }}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.summary.label(class="form-control-label mb-4") }}
            {% if form.summary.errors %}
                {{ form.summary(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.summary.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.summary(class="form-control form-control-lg") }}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.avg_time.label(class="form-control-label mb-4") }}
            {% if form.avg_time.errors %}
                {{ form.avg_time(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.avg_time.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.avg_time(class="form-control form-control-lg") }}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.volume.label(class="form-control-label mb-4") }}
            {% if form.volume.errors %}
                {{ form.volume(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.volume.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.volume(class="form-control form-control-lg") }}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.pain_point.label(class="form-control-label mb-4") }}
            {% if form.pain_point.errors %}
                {{ form.pain_point(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.pain_point.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.pain_point(class="form-control form-control-lg") }}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.pain_point_time.label(class="form-control-label mb-0") }}
            {% if form.pain_point_time.errors %}
                {{ form.pain_point_time(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.pain_point_time.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.pain_point_time(class="form-control form-control-lg") }}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </div>
    </form>
</div>

{% endblock content %}

bua/templates/tasks/squad_details.html
{% extends "main/_layout.html" %}
{% block additional_css %}
<link rel="stylesheet" href="/static/css/home.css"/>
<link rel="stylesheet" href="/static/css/your_squad.css"/>
{% endblock %}

{% block content %}

    <div class="details">
        <div class="content-details">
            <div class="hero">
                <div class="col-sm-8">
                    <div class="install sub-hero">
                        <div class="hero-inner">
                        <h1> Task For: {{ squad.squadname }} </h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="bua-stats">

        <div class="stat"> Activities: {{ "{:,}".format(activity_count) }} </div>

        <div class="stat"> Current Workloads: {{ "{0:.1f}".format(squad_ftes) }} <small>FTEs</small>  </div>


        <div class="stat"> Standard Activities: {{ "{0:.1f}".format(standard_ftes)}} <small>FTEs</small>  </div>





    </div>

    <div class="content-section">
        <h2> Tasks Overview</h2>


        <div class="table-responsive">
            <table class="table table-sm table-condensed table-striped" id="activities">
            <thead>
                <tr>
                    <th scope="col">Activity</th>
                    <th scope="col">Tool</th>
                    <th scope="col">Volume per Month</th>
                    <th scope="col">Min per Transaction</th>
                    <th scope="col">Feedback</th>


                </tr>
            </thead>
            <tbody>
            {% for t in tasks %}
                <tr id={{ t.id }}>
                    <td scope="col"> {{ t.activity }}</td>
                    <td scope="col"> {{ t.tool }} </td>
                    <td scope="col"> {{ t.volume }} </td>
                    <td scope="col"> {{ t.avg_time }} </td>
                    <td scope="col"> {{ t.pain_point }} </td>

                    <div class="buttons">
                        <td scope="col"> <a class="btn btn-secondary btn-sm m-1" href="/task/{{ t.id }}">Detail</a> </td>

                    </div>
                </tr>
            {% endfor %}
            <div class="todo">
            </tbody>
        </table>
                     <td scope="col"> <a class="btn btn-success btn-sm m-1" href="{{ url_for('todo.to_do') }}">Actions & Savings </a></td>

        </div>

    </div>




{% endblock content %}

bua/templates/tasks/task.html
{% extends "main/_layout.html" %}
{% block title %} Details {% endblock %}
{% block additional_css %}
<link rel="stylesheet" href="/static/css/details.css"/>
{% endblock %}

{% block content %}
    <div class="details">
        <div class="content-details">
            <div class="hero">
                <div class="col-sm-8">
                    <div class="install sub-hero">
                        Product:
                        {{ task.product }}
                    </div>


                </div>
            </div>
        </div>

        <div class="stats">
            <div class="col-sm-1"></div>
            <b>General Task Perform:</b>
            <a href="#" class="stats">{{ task.activity }}</a>
            <div class="col-sm-10">

            </div>
        </div>

        <div class="project-list container">
            <div class="row">
                <div class="col-sm-3 nav-sidebar-section">


                    <h4> Details: </h4>
                    <h3>Training & Recording Links</h3>
                    <a href="https://ibm.ent.box.com/folder/61045950947">
                        <i class="fa fa-home" aria-hidden="true"></i>
                        Link
                    </a>
                    <hr>

                    <h3>Statistics</h3>
                    <p></p>
                     <h6> Monthly Volume: {{ task.volume }}</h6>
                    <h6> Time per Transaction: {{ task.avg_time }} min.</h6>
                    <p></p>

                    <h6> Total FTEs for Annual Activity: <prep> {{ "{0:.1f}".format(ftes) }} </prep></h6>
                    <p></p>
                    <hr>

                    <div>
                        <h3> Support </h3>
                        <h6>Tools: {{ task.tool }}</h6>

                    </div>
                    <hr>

                    <h3>Known Pain Points</h3>
                    <div class="Details">
                        <h6> Pain Time per Transaction:</h6>
                        <h5> {{ (waste_time) }} min. per transaction</h5>
                    </div>
                    <hr>

                </div>

                <div class="col-sm-7">

                    <h2>Activity description</h2>

                    <pre>Summary | Detail Description of the Activity</pre>
                    <p class="summary">
                       {{ task.summary }}
                    </p>

                    <div class="btn1">
                         <div class="buttons">
                        <td scope="col"> <a class="btn btn-secondary btn-sm mt-1 mb-1" href="/task/{{ task.id }}/update">Edit</a> </td>
                        <td scope="col"> <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button></td>
                        <!-- Modal -->

                        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="deleteModalLabel">Delete Task?</h5>

                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>

                                    </div>

                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

                                       <form action="{{ url_for('tasks.delete_task', task_id=task.id) }}" method="POST">

                                            <input class="btn btn-danger" type="submit" value="Delete">
                                        </form>
                                    </div>

                                </div>
                            </div>
                        </div>


                    </div>

                    </div>

                </div>

                <div class="col-sm-1"></div>

                <div class="opportunity">
                    <h3>Feedback: </h3>
                    <p><h6>{{ task.pain_point }}</h6> </p>
                </div>


            </div>
        </div>

    </div>
    </div>

{% endblock %}

bua/templates/tasks/templates.html
{% extends "main/share/../main/_layout.html" %}
{% block title %} Index {% endblock %}
{% block additional_css %}
<link rel="stylesheet" href="/static/css/account.css"/>

{% endblock %}

{% block content %}

<div class="bua-stats">
        <div class="stat"> {{ "{0:.1f}".format(saving_ftes) }} Total Savings</div>

        <div class="stat"> {{ "{:,}".format(incomplete_count) }} Actions Pending</div>

        <div class="stat"> {{ "{:,}".format(complete_count) }} Actions Completed</div>

</div>

<div class="form-group2">
    <div class="col-sm-12 nav-sidebar-section">
        <div> <h4>Create an Action</h4>  </div>

        <div class="form-group">
            {{ form.goal.label(class="form-control-label") }}
            {% if form.goal.errors %}
                {{ form.goal(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.goal.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.goal(class="form-control form-control-lg") }}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.saving.label(class="form-control-label") }}
            {% if form.saving.errors %}
                {{ form.saving(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.saving.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.saving(class="form-control form-control-lg") }}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </div>

 <div class="content-section2">
  <div class="col-sm-12 nav-sidebar-section">
     <div> <h4>Create an Action</h4>  </div>
    <form action="{{ url_for('todo.add') }}" method="POST">
        <input type="text" class="form-control-label-1" placeholder="Write a New Goal" name="goal_item">
        <input type="text" class="form-control-label-2" placeholder="Target savings Hours per Month" name="saving_item">
        <input type="submit" class="btn btn-info btn-sm m-1" value="Add Action">
    </form>
  </div>

 </div>

  <div class="content-section2">
      <div class="col-sm-12 nav-sidebar-section">
          <div class="table-responsive">
              <h4>Pending Actions</h4>
              <table class="table" id="activities">
                  <thead>
                  <tr>
                      <th scope="col">Action</th>
                      <th scope="col">Projected Savings</th>
                  </tr>
                  </thead>
                  <tbody>
                  {% for todo in incomplete %}
                      <tr id={{ todo.id }}>
                          <td scope="col"> {{ todo.goal }}</td>
                          <td scope="col"> {{ todo.saving }} </td>

                          <div class="button">
                              <td scope="col"> <a class="btn btn-success btn-sm m-1" href="{{ url_for('todo.complete', id=todo.id) }}">Mark Complete</a> </td>

                              <td scope="col"> <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button></td>
                              <!-- Modal -->

                              <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="deleteModalLabel">Delete Task?</h5>

                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>

                                    </div>

                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <form action="{{ url_for('todo.delete_goal', id=id) }}" method="POST">
                                            <input class="btn btn-danger" type="submit" value="Delete">
                                        </form>
                                    </div>

                                </div>
                            </div>
                        </div>


                          </div>
                      </tr>
                {% endfor %}
                </tbody>
            </table>
           </div>
      </div>
  </div>

  <div class="content-section2">
      <div class="col-sm-12 nav-sidebar-section">
          <div class="table-responsive">
              <h4>Completed Actions</h4>
              <table class="table" id="activities">
                  <thead>
                  <tr>
                      <th scope="col">Completed Action</th>
                      <th scope="col">Savings Achieved | Hours per Month</th>
                  </tr>
                  </thead>
                  <tbody>
                  {% for todo in complete %}
                      <tr id={{ todo.id }}>
                          <td scope="col"> {{ todo.goal }}</td>
                          <td scope="col"> {{ todo.saving }} </td>

                          <div class="button">
                              <td scope="col"> <a class="btn btn-danger btn-sm m-1" href="{{ url_for('todo.incomplete', id=todo.id) }}">Mark Incomplete</a> </td>
                          </div>
                      </tr>
                  {% endfor %}
                  </tbody>
              </table>
          </div>
      </div>
  </div>


 <div class="content-section2">
      <div class="col-sm-12 nav-sidebar-section">
          <div class="table-responsive">
              <h4>Pending Actions</h4>
              <table class="table" id="activities">
                  <thead>
                  <tr>
                      <th scope="col">Action</th>
                      <th scope="col">Projected Savings</th>
                  </tr>
                  </thead>
                  <tbody>
                  {% for todo in incomplete %}
                      <tr id={{ todo.id }}>
                          <td scope="col"> {{ todo.goal }}</td>
                          <td scope="col"> {{ todo.saving }} </td>

                          <div class="button">
                              <td scope="col"> <a class="btn btn-success btn-sm m-1" href="{{ url_for('todo.complete', id=todo.id) }}">Mark Complete</a> </td>

                              <td scope="col"> <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button></td>
                              <!-- Modal -->

                              <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="deleteModalLabel">Delete Task?</h5>

                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>

                                    </div>

                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <form action="{{ url_for('todo.delete_goal', id=id) }}" method="POST">
                                            <input class="btn btn-danger" type="submit" value="Delete">
                                        </form>
                                    </div>

                                </div>
                            </div>
                        </div>


                          </div>
                      </tr>
                {% endfor %}
                </tbody>
            </table>
           </div>
      </div>
  </div>

  <div class="content-section2">
      <div class="col-sm-12 nav-sidebar-section">
          <div class="table-responsive">
              <h4>Completed Actions</h4>
              <table class="table" id="activities">
                  <thead>
                  <tr>
                      <th scope="col">Completed Action</th>
                      <th scope="col">Savings Achieved | Hours per Month</th>
                  </tr>
                  </thead>
                  <tbody>
                  {% for todo in complete %}
                      <tr id={{ todo.id }}>
                          <td scope="col"> {{ todo.goal }}</td>
                          <td scope="col"> {{ todo.saving }} </td>

                          <div class="button">
                              <td scope="col"> <a class="btn btn-danger btn-sm m-1" href="{{ url_for('todo.incomplete', id=todo.id) }}">Mark Incomplete</a> </td>
                          </div>
                      </tr>
                  {% endfor %}
                  </tbody>
              </table>
          </div>
      </div>
  </div>




    <div>.</div>

    <div>.</div>

<div class="activities-list">
        <div class="row">
            <div class="col-md-3"></div>

            <div class="col-md-7">
                <h2> Newest Activities</h2>
                <div class="subtitle">
                    List of Latest Activities and Tasks
                </div>

                {% for task in tasks.items %}
                    <article class="media content-section">
                        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + task.author.image_file) }}">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="{{ url_for('squads.user_tasks', squadname=task.author.squadname) }}">{{ task.author.squadname }}</a>
                                <small class="text-muted">{{ task.date_posted.strftime('%y-%m-%d') }}</small>
                            </div>
                            <h2><a class="article-title" href="{{ url_for('tasks.task', task_id=task.id) }}">{{ task.product }}</a></h2>
                            <p class="article-content">{{ task.activity }}</p>
                        </div>
                    </article>
                {% endfor %}

                {% for page_num in tasks.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
                    {% if page_num %}
                        {% if tasks.page == page_num %}
                            <a class="btn btn-info mb-4" href="{{ url_for('main.home', task=page_num) }}">{{ page_num }}</a>
                        {% else %}
                            <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', task=page_num) }}">{{ page_num }}</a>
                        {% endif %}
                        ...
                    {% else %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
   </div>


{% endblock content %}